---
- name: Update packages on Ubuntu servers
  hosts: ubuntu_servers  # Ersetzen Sie 'ubuntu_servers' durch Ihre tatsächliche Gruppe oder Host(s)
  become: yes  # Erforderlich, um sudo-Berechtigungen für das Aktualisieren der Pakete zu erhalten

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes  # Entfernt automatisch nicht mehr benötigte Pakete
        autoclean: yes   # Löscht alte Paketdateien aus dem Cache
      register: apt_upgrade_result  # Registrieren des Ergebnisses der Paketaktualisierung

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600  # Timeout für den Neustart in Sekunden (optional)
        connect_timeout: 30  # Timeout für den Neustartversuch in Sekunden (optional)
        reboot_timeout_is_seconds: true  # Verwenden Sie Sekunden für den Timeout (optional)
      when: apt_upgrade_result.changed  # Führt den Neustart nur aus, wenn Pakete aktualisiert wurden
