---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes

  tasks:
    - name: Clear apt locks if they exist
      become: yes
      shell:
        cmd: |
          sudo rm -f /var/lib/apt/lists/lock
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -f /var/lib/dpkg/lock*
      ignore_errors: yes

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        allow_unauthenticated: yes
        #dpkg_options: "force-confdef force-confold"
      register: apt_upgrade_result
      failed_when: apt_upgrade_result.failed
      changed_when: apt_upgrade_result.changed

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 30
      when: apt_upgrade_result.changed
