---
- name: Update and upgrade specific packages on Ubuntu servers
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade python3-update-manager package
      apt:
        name: python3-update-manager
        state: latest

    - name: Upgrade update-manager-core package
      apt:
        name: update-manager-core
        state: latest

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confdef,force-confold'
      register: apt_upgrade_result

    - debug:
        var: apt_upgrade_result.changed

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 30
        reboot_timeout_is_seconds: true
      when: apt_upgrade_result.changed
