---
- name: Update and upgrade all packages including foreign packages on Ubuntu servers
  hosts: deine_host_gruppe
  become: yes
  become_method: sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confdef,force-confold'
      register: apt_upgrade_result

    - debug:
        var: apt_upgrade_result.changed

    - name: Upgrade Fremdpakete
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confdef,force-confold'
        allow_unauthenticated: yes
        only_upgrade: yes

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 30
        reboot_timeout_is_seconds: true
      when: apt_upgrade_result.changed
