---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Clear apt locks if they exist
      become: yes
      become_user: root
      shell: |
        rm -f /var/lib/apt/lists/lock
        rm -f /var/cache/apt/archives/lock
        rm -f /var/lib/dpkg/lock*
      ignore_errors: yes

    - name: Update apt package cache
      become: yes
      become_user: root
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      become: yes
      become_user: root
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        allow_unauthenticated: yes
      register: apt_upgrade_result
      failed_when: apt_upgrade_result.failed
      changed_when: apt_upgrade_result.changed

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 30
      when: apt_upgrade_result.changed
