---
- name: Update and upgrade packages on Ubuntu servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confdef,force-confold'
      register: apt_upgrade_result

    - debug:
        var: apt_upgrade_result.changed

    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 30
        reboot_timeout_is_seconds: true
      when: apt_upgrade_result.changed

    - name: Run apt update and full-upgrade
      ansible.builtin.shell: sudo apt update && sudo apt full-upgrade -y
      become: yes
      become_method: sudo
      when: apt_upgrade_result.changed

