---
- name: Update packages on Ubuntu servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      register: apt_upgrade_result
    - name: Reboot if packages were upgraded
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: apt_upgrade_result.changed
