- hosts: test
  tasks:
    - name: Get system information
      ansible.builtin.shell: "hostnamectl"
      register: hostname_output

    - name: Send output via email
      ansible.builtin.mail:
        host: imap.hispeed.ch
        port: 587
        username: s.berger@hispeed.ch
        password: 
        to: sascha.berger@santismail.ch
        subject: Ansible Output
        body: "{{ hostname_output.stdout }}"
        secure: starttls
      delegate_to: localhost

