- hosts: test
  tasks:
    - name: Get system information
      ansible.builtin.shell: "hostnamectl"
      register: hostname_output

    - name: Save output to file on remote server
      ansible.builtin.copy:
        content: "{{ hostname_output.stdout }}"
        dest: "/home/target2/ausgabedatei.txt"
      delegate_to: remote_server

