# playbook.yml

- hosts: test  # Hier sollten die richtigen Hosts angegeben werden, auf denen du die Aufgaben ausführen möchtest
  tasks:
    - name: Get system information
      ansible.builtin.shell: "hostnamectl"
      register: hostname_output

    - name: Write output to file
      ansible.builtin.copy:
        content: "{{ hostname_output.stdout }}"
        dest: "/home/target1/ausgabedatei.txt"
