---
- name: Sammeln von Daten von Servern und Speichern in HTML-Dateien
  hosts: all
  gather_facts: no
  tasks:
    - name: Uptime sammeln
      command: uptime
      register: uptime_output

    - name: Logs sammeln (letzte 10 Zeilen von /var/log/syslog)
      command: tail -n 10 /var/log/syslog
      register: log_output

    - name: HTML-Verzeichnis erstellen, falls nicht vorhanden
      delegate_to: localhost
      file:
        path: /home/target1/testtt
        state: directory
        mode: '0755'

    - name: HTML-Seite erstellen
      delegate_to: localhost
      template:
        src: template.html.j2
        dest: /home/html_data/output_{{ inventory_hostname }}.html
      vars:
        uptime: "{{ uptime_output.stdout }}"
        logs: "{{ log_output.stdout }}"
