- hosts: test
  tasks:
    - name: Get system information
      ansible.builtin.shell: "hostnamectl"
      register: hostname_output

    - name: Send output to web application
      ansible.builtin.uri:
        url: "http://localhost:5000/save_output"
        method: POST
        body: "{{ hostname_output.stdout }}"
        body_format: raw
        status_code: 200

