---
- hosts: test
  tasks:
    - name: Get system information from test servers
      ansible.builtin.shell: "hostnamectl"
      register: hostname_output
      delegate_to: "{{ inventory_hostname }}"

    - name: Save output to temporary file on test servers
      ansible.builtin.copy:
        content: "{{ hostname_output.stdout }}"
        dest: "/tmp/hostname_output_{{ inventory_hostname }}.txt"
      delegate_to: "{{ inventory_hostname }}"

- hosts: remote_servers
  tasks:
    - name: Ensure /tmp directory exists on remote server
      ansible.builtin.file:
        path: "/tmp"
        state: directory
      delegate_to: remote_server

    - name: Transfer output from each test server to individual files
      ansible.builtin.copy:
        src: "/tmp/hostname_output_{{ item }}.txt"
        dest: "/home/target2/hostname_output_{{ item }}.txt"
        remote_src: true
        force: yes  # Erzwingt die Übertragung auch dann, wenn die Datei bereits existiert
      with_items: "{{ groups['test'] }}"
      delegate_to: remote_server
      ignore_errors: true
