---
- name: Fail2ban-Konfiguration verwalten
  hosts: all
  become: yes
  tasks:
    - name: Sicherstellen, dass fail2ban installiert ist
      apt:
        name: fail2ban
        state: present
    - name: Fail2ban konfigurieren
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 3
          [sshd]
          enabled = true
    - name: Fail2ban neu starten
      service:
        name: fail2ban
        state: restarted
