---
- name: Wichtige Dateien sichern
  hosts: all
  become: yes
  vars:
    backup_dest: /backup/
  tasks:
    - name: Sicherungsverzeichnis erstellen
      file:
        path: "{{ backup_dest }}"
        state: directory
        mode: '0755'
    - name: Webseiten-Dateien sichern
      synchronize:
        src: /var/www/html/
        dest: "{{ backup_dest }}/website/"
        archive: yes
    - name: MySQL-Datenbanken sichern
      mysql_db:
        name: "{{ item }}"
        state: dump
        target: "{{ backup_dest }}/db_backup/{{ item }}.sql"
      loop: "{{ lookup('mysql_db', 'name', wantlist=True) }}"
    - name: E-Mail-Daten sichern
      synchronize:
        src: /var/mail/
        dest: "{{ backup_dest }}/mail/"
        archive: yes
