---
- hosts: server
  become: yes
  tasks:
    - name: Check whoami with become
      command: whoami
      register: whoami_output

    - name: Debug whoami output
      debug:
        var: whoami_output

