---
- name: Spam- und Virendefinitionen aktualisieren
  hosts: all
  become: yes
  tasks:
    - name: Spamassassin-Regeln aktualisieren
      command: sa-update
      notify:
        - spamassassin neu starten
    - name: ClamAV-Definitionen aktualisieren
      command: freshclam
      notify:
        - clamav neu starten

  handlers:
    - name: spamassassin neu starten
      service:
        name: spamassassin
        state: restarted
    - name: clamav neu starten
      service:
        name: clamav-daemon
        state: restarted
