---
- name: Test playbook to find ansible.cfg path
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Use ansible-config to find path to ansible.cfg
      command: ansible-config --list | grep CONFIG_FILE | awk -F '= ' '{print $2}'
      register: ansible_config_output
      failed_when:
        - ansible_config_output.rc != 0  # Fehler, wenn der Befehl nicht erfolgreich ist
        - ansible_config_output.stdout_lines | length != 1  # Genau eine Zeile erwartet

    - name: Set fact with ansible.cfg path
      set_fact:
        ansible_cfg: "{{ ansible_config_output.stdout }}"

    - name: Show ansible_cfg value
      debug:
        var: ansible_cfg


