- name: Alle Pakete auf Ubuntu-Servern aktualisieren
  hosts: all
  become: yes
  tasks:
    - name: APT-Cache aktualisieren
      apt:
        update_cache: yes
    - name: Alle Pakete upgraden
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
